spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./applicationdb;MODE=MYSQL;AUTO_SERVER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS STARWARSRSN
    username: user
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: STARWARSRSN
        format_sql: true
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: src/main/resources/db/migration/V1__CREATE_SCHEMA.sql

  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

server:
  port: 8080

springdoc:
  swagger-ui:
    operationsSorter: method